    PROGRAM MODULAR.APPROACHER
    CRT "ENTER THE ACCOUNT NUMBER: "
    INPUT CUST_ID

    CALL  MODULAR.APPROACH(CUST_ID,CUST_CAT,CUST_CURR)
    PRINT "CURRENCY: ": FMT(CUST_CURR, 'MCP')
    PRINT "CATEGORY: ": FMT(CUST_CAT, 'MCP')
END
